TELEGRAM_BOT_TOKEN="8424327971:AAGsuuQEsDbSVHmbZXGprxnU-lROmKlNmFU"
TELEGRAM_CHAT_ID="252191346"
SMTP_USER="poke.hunting62@gmail.com"
SMTP_PASS="kydbjztpxetqcgoh"
EMAIL_TO="ombaiakas62@gmail.com"
STREAMLINE_API_KEY="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"
